print("--- DETERMINANT CALCULATOR --- \n") 
print("NB : DETERMINANT IS ONLY DEFINED FOR SQUARE MATRICES.  \n ")
print("Select the order of your matrix = ")
print("1-- 2 x 2 Matrix")
print("2-- 3 x 3 Matrix \n")
order = int(input(""))
if order == 1:
    a_11 = int(input( " Enter the value of a 11 = "))
    a_12 = int(input( " Enter the value of a 12 = "))
    a_21 = int(input( " Enter the value of a 21 = "))
    a_22 = int(input( " Enter the value of a 22 = "))
    print(" Your 2 X 2 matrix is ")
    print(f"| {a_11} {a_12} |")
    print(f"| {a_21} {a_22} |")
    determinant = a_11*a_22-a_21*a_12
    print(f" DETERMINANT OF THE MATRIX IS {determinant} ")
elif order == 2:
    a = int(input( " Enter the value of a 11 = "))
    b = int(input( " Enter the value of a 12 = "))
    c = int(input( " Enter the value of a 12 = "))
    d = int(input( " Enter the value of a 13 = "))
    e = int(input( " Enter the value of a 21 = "))
    f = int(input( " Enter the value of a 22 = "))
    g = int(input( " Enter the value of a 23 = "))
    h = int(input( " Enter the value of a 31 = "))
    i = int(input( " Enter the value of a 32 = "))
    print(" Your 3 X 3 matrix is ")
    print(f"| {a} {b} {c}|")
    print(f"| {d} {e} {f}|")
    print(f"| {g} {h} {i}|")
    determinant = a((e*i)−(f*h))−b((d*i)−(f*g))+c((d*h)−(e*g))
    print(f" DETERMINANT OF THE MATRIX IS {determinant} ")
else:
    print(" Invalid option")
